### ISSUE TITLE
Is it possible to have the each surah folder contain all the verses in one page 

### ISSUE THREAD

**Issue by aaaltair** [omeiirr/quran-obsidian-template#1]
This would be really useful if we can have all the ayat of the surah in one page to make better notes. Right now it seems too overwhelming and tedious to go to one page to the next.

**Comment by omeiirr** [comment]
That would become a problem for the earlier Surahs which are quite lengthy, especially considering that the single file containing the verses along with their explanations would become very lengthy.

Moreover, having each ayat in a separate file allows you to reference and link it in other pages, a key feature of Obsidian. Having all Ayats in a single file would make this important feature infeasible.
